### PR TITLE
Update visual_chatgpt.py

### PR DESCRIPTION
**Pull request by Khaleelhabeeb**
I've added comments to the visual_chatgpt.py to help make the code more readable and understandable. Each comment explains the purpose of a specific block of code and its input/output. Thanks!

### CODE REVIEW

**Comment by qoft** [comment]
bro just wants to he in the contributors 💀

**Comment by Khaleelhabeeb** [comment]
Bro just want to comment 😂😂

**Comment by Khaleelhabeeb** [comment]
> bro just wants to be in the contributors 💀 

Brrrr

**Comment by chenfei-wu** [comment]
Thanks!

**Pull request closed without merging**
