### PR TITLE
fix: add opencv-python as required lib

### PR DESCRIPTION
**Pull request by DjangoPeng**
Facing same issue https://github.com/microsoft/visual-chatgpt/issues/29

I believe that adding the `opencv-python` library to the requirements.txt file should work.

### CODE REVIEW

**Comment by DjangoPeng** [comment]
@Moymix PTAL

**Comment by quangogster** [comment]
I had to remove `opencv-contrib-python==4.3.0.36` and replace with opencv-python for mines to install.  Is this recommended?

**Comment by DjangoPeng** [comment]
Actually `opencv-contrib-python` is different from `opencv-python`. 

So I'd like to keep it.

**Comment by DjangoPeng** [comment]
Close because @chenfei-wu has added `opencv-python` into requirement.txt

**Pull request closed without merging**
