### PR TITLE
Optimized the visual-chatgpt.py Code Which makes it a good clean code

### PR DESCRIPTION
**Pull request by BinayakJha**
**I have optimized the visual-chatgpt.py code which has made it more cleaner and also easy to understand**

### CODE REVIEW

**Comment by BinayakJha** [comment]
@microsoft-github-policy-service agree

**Review by KnoBuddy — APPROVED** [review]

**Review by KnoBuddy — COMMENTED** [review]
lgtm

**Comment by BinayakJha** [comment]
@KnoBuddy Thankyou for reviewing and approving the changes. 

Waiting for it to be merged now:)

**Comment by BinayakJha** [comment]
I have resolved the conflicts in my code which had been due to the recent update in the main code.

**Pull request merged**
